import CoreGraphics
import Foundation
import WebP

/// Decodes the bundled animated WebP with `WebPAnimatedDecoder` for the Animated WebP tab.
/// `bouncing-ball.webp` is generated by `Demo/Scripts/make-bouncing-ball.swift`.
enum AnimatedWebPSample {
    static let resourceName = "bouncing-ball"

    static let code = """
        var decoder = try WebPAnimatedDecoder(webPData) // .rgbA
        let info = decoder.info // canvas size, frameCount, loopCount
        while let frame = try decoder.nextFrame() {
            let image = try frame.makeCGImage()
            let start = frame.timing.startTimeMilliseconds
            let duration = frame.timing.durationMilliseconds
        }
        """

    static func load() throws -> AnimatedWebPPlayback {
        guard let url = Bundle.main.url(forResource: resourceName, withExtension: "webp") else {
            throw SampleError.missingResource
        }
        let data = try Data(contentsOf: url)
        let clock = ContinuousClock()
        var info: WebPAnimationInfo?
        var frames: [AnimatedWebPPlayback.Frame] = []
        let decodeTime = try clock.measure {
            var decoder = try WebPAnimatedDecoder(data)
            info = decoder.info
            while let frame = try decoder.nextFrame() {
                frames.append(.init(image: try frame.makeCGImage(), timing: frame.timing))
            }
        }
        guard let info else { throw SampleError.missingResource }
        return AnimatedWebPPlayback(info: info, frames: frames, fileSize: data.count, decodeTime: decodeTime)
    }

    enum SampleError: Error {
        case missingResource
    }
}

struct AnimatedWebPPlayback {
    struct Frame: Identifiable {
        let image: CGImage
        let timing: WebPAnimationFrameTiming
        var id: Int { timing.index }
    }

    let info: WebPAnimationInfo
    let frames: [Frame]
    let fileSize: Int
    let decodeTime: Duration

    var totalMilliseconds: Int {
        frames.last.map { $0.timing.startTimeMilliseconds + $0.timing.durationMilliseconds } ?? 0
    }

    /// The frame shown at `elapsed` milliseconds, honoring each frame's own duration.
    func frameIndex(atMilliseconds elapsed: Int) -> Int {
        let time = loopedTime(elapsed)
        return frames.lastIndex { $0.timing.startTimeMilliseconds <= time } ?? 0
    }

    /// The frame shown at `elapsed` milliseconds if every frame lasted the same time,
    /// as with `UIImage.animatedImage(with:duration:)`.
    func uniformFrameIndex(atMilliseconds elapsed: Int) -> Int {
        let time = loopedTime(elapsed)
        return min(time * frames.count / max(totalMilliseconds, 1), frames.count - 1)
    }

    private func loopedTime(_ elapsed: Int) -> Int {
        guard totalMilliseconds > 0 else { return 0 }
        if info.loopCount > 0, elapsed >= totalMilliseconds * info.loopCount {
            return totalMilliseconds - 1
        }
        return elapsed % totalMilliseconds
    }
}
