name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  macos-build-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Show Swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  linux-build-test:
    runs-on: ubuntu-latest
    container: swift:6.2
    steps:
      - uses: actions/checkout@v4
      - name: Show Swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  ios-package-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Show Swift version
        run: swift --version
      - name: Build package for iOS
        run: xcodebuild -scheme WebP-Package -destination 'generic/platform=iOS' -sdk iphoneos build
